II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/biblio3auth/biblio3/biblio3/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from .views import *
from .initcmds import *

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$|^home\/$",biblio3_home,name="home"),

    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),

    path("registerb/",BiblioCreateView.as_view(), name="registerb"),

    path("gestione/", include("gestione.urls"))
]

#erase_db()
init_db()

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/biblio3auth/biblio3/gestione/urls.py
from django.urls import path
from .views import *

app_name = "gestione"

urlpatterns = [
    path("", gestione_home, name="home"),
    path("listalibri/", LibroListView.as_view(),name="listalibri"),
    path("ricerca/", search, name="cercalibro"),
    path("ricerca/<str:sstring>/<str:where>/", LibroRicercaView.as_view(), name="ricerca_risultati"),
    path("prestito/<pk>/", prestito, name="prestito"),
    path("situation/", my_situation, name="situation"),
    path("restituzione/<pk>/", RestituisciView.as_view(), name="restituzione"),

    path("situationb/", BiblioSituationView.as_view(),name="situationb"),
    path("detailb/<pk>/", BiblioDetailView.as_view(), name="detailb"),
    path("crea_libro/",CreateLibroView.as_view(),name="crealibro"),
    path("crea_copia/",CreateCopiaView.as_view(),name="creacopia"),

    path("ricerca/gethint/", get_hint, name="get_hint")
]

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/biblio3auth/biblio3/gestione/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Libro(models.Model):
    titolo = models.CharField(max_length=200)
    autore = models.CharField(max_length=50)
    pagine = models.IntegerField(default=100)

    def disponibile(self):
        if self.copie.filter(data_prestito=None).count() > 0:
            return True
        return False
        
    def __str__(self):
        disp = self.copie.filter(data_prestito=None).count()
        out = self.titolo + " di " + self.autore + " ha " + str(self.copie.all().count()) + " copie" + " di cui " + str(disp) + " disponibili"
        return out

    class Meta:
        verbose_name_plural = "Libri"

class Copia(models.Model):
    data_prestito = models.DateField(default=None,null=True,blank=True)
    libro = models.ForeignKey(Libro,on_delete=models.CASCADE,related_name="copie")
    utente = models.ForeignKey(User, on_delete=models.PROTECT,blank=True,null=True,default=None,related_name="copie_in_prestito")

    def chi_in_prestito(self):
        if self.utente == None: return None
        return self.utente.username

    def __str__(self):
        return "Copia di " + self.libro.titolo + " di " + self.libro.autore + " in prestito dal " + str(self.data_prestito) 

    class Meta:
        verbose_name_plural = "Copie"

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/biblio3auth/biblio3/gestione/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import *

class SearchForm(forms.Form):

    CHOICE_LIST = [("Titolo","Cerca tra i titoli"), ("Autore","Cerca tra gli autori")]
    helper = FormHelper()
    helper.form_id = "search_crispy_form"
    helper.form_method = "POST"
    helper.add_input(Submit("submit","Cerca"))
    search_string = forms.CharField(label="Cerca qualcosa",max_length=100, min_length=3, required=True)
    search_where = forms.ChoiceField(label="Dove?", required=True, choices=CHOICE_LIST)


class CreateLibroForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_id = "addlibro_crispy_form"
    helper.form_method = "POST"
    helper.add_input(Submit("submit","Aggiungi Libro"))

    class Meta:
        model = Libro
        fields = ["titolo","autore","pagine"]

class CreateCopiaForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_id = "addcopia_crispy_form"
    helper.form_method = "POST"
    helper.add_input(Submit("submit","Aggiungi Copia"))

    class Meta:
        model = Copia
        fields = ["libro"]

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/biblio3auth/biblio3/gestione/views.py
from .models import *
from .forms import *
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.http import HttpResponse

# pipenv install django-braces
from braces.views import GroupRequiredMixin

# Create your views here.

def gestione_home(request):
    return render(request,template_name="gestione/home.html")


class LibroListView(ListView):
    titolo = "La nostra biblioteca possiede"
    model = Libro
    template_name = "gestione/lista_libri.html"


def search(request):

    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            sstring = form.cleaned_data.get("search_string")
            where = form.cleaned_data.get("search_where")
            return redirect("gestione:ricerca_risultati", sstring, where)
    else:
        form = SearchForm()

    return render(request,template_name="gestione/ricerca.html",context={"form":form})
    #return render(request,template_name="gestione/ricerca_ajax.html",context={"form":form})

class LibroRicercaView(LibroListView):
    titolo = "La tua ricerca ha dato come risultato"

    def get_queryset(self):
        sstring = self.request.resolver_match.kwargs["sstring"] 
        where = self.request.resolver_match.kwargs["where"]

        if "Titolo" in where:
            qq = self.model.objects.filter(titolo__icontains=sstring)
        else:
            qq = self.model.objects.filter(autore__icontains=sstring)

        return qq

@login_required
def prestito(request, pk):
    l = get_object_or_404(Libro,pk=pk)

    errore = "NO_ERRORS"
    if l.disponibile() == False:
        errore = "Non vi sono copie disponibili"

    copie_in_prestito = request.user.copie_in_prestito.all()

    if copie_in_prestito.filter(libro__autore__iexact=l.autore,libro__titolo__iexact=l.titolo).count() != 0:
        errore = "Hai già una copia di quel libro!"

    copia = None
    if errore == "NO_ERRORS":
        for c in l.copie.filter(data_prestito=None):
            c.data_prestito = timezone.now()
            c.utente = request.user
            copia = c
            break

    if copia != None:       
        try:
            copia.save()
            print("Copia salvata con successo " + str(copia) + " in prestito: " + copia.chi_in_prestito())
        except Exception as e:
            errore = "Errore nella registrazione del prestito"
            print(errore + " " + str(e))

    return render(request,"gestione/prestito.html",{"errore":errore,"libro":l,"copia":copia})

@login_required
def my_situation(request):
    user = get_object_or_404(User, pk=request.user.pk)
    copie = user.copie_in_prestito.all()
    ctx = { "listacopie" : copie }
    return render(request,"gestione/situation.html",ctx)

class RestituisciView(LoginRequiredMixin, DetailView):
    model = Copia
    template_name = "gestione/restituzione.html"
    errore = "NO_ERRORS"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        c = ctx["object"]

        if c.data_prestito != None:

            if c.utente.pk != self.request.user.pk:
                self.errore = "Non puoi restituire un libro non tuo!"

        else:
            self.errore = "Libro attualmente non in prestito"

        if self.errore == "NO_ERRORS":
            try:
                c.data_prestito = None
                c.utente = None
                c.save()
            except Exception as e:
                print("Errore! " + str(e))
                self.errore = "Errore nell'operazione di restituzione"

        return ctx

def get_hint(request):

    response = request.GET["q"]

    if(request.GET["w"]=="Titolo"):
        q = Libro.objects.filter(titolo__icontains=response)
        if len(q) > 0: 
            response = q[0].titolo
    else: 
        q = Libro.objects.filter(autore__icontains=response)
        if len(q) > 0: 
            response = q[0].autore

    return HttpResponse(response)

#Views per soli Bibliotecari 

class BiblioSituationView(GroupRequiredMixin, ListView):
    group_required = ["Bibliotecari"]
    model = Libro
    template_name = "gestione/situationb.html"

class BiblioDetailView(GroupRequiredMixin, DetailView):
    group_required = ["Bibliotecari"]
    model = Libro
    template_name = "gestione/detailb.html"

class CreateLibroView(GroupRequiredMixin, CreateView):
    group_required = ["Bibliotecari"]
    title = "Aggiungi un libro alla biblioteca"
    form_class = CreateLibroForm
    template_name = "gestione/create_entry.html"
    success_url = reverse_lazy("gestione:home")

class CreateCopiaView(CreateLibroView):
    title = "Aggiungi una Copia ad un libro"
    form_class = CreateCopiaForm

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/biblio3auth/biblio3/gestione/templates/gestione/create_entry.html
{% extends 'basebs.html' %}

{% block title %} {{view.title}} {% endblock %} 

{% load crispy_forms_tags %} 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

{% block header1 %}
  <h1> {{view.title}} </h1>
{% endblock %}

{% block content %} 

<br>

<div class="d-flex justify-content-center">

  {% crispy form %}

</div>
<br>


<br>

{% endblock %}

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/biblio3auth/biblio3/gestione/templates/gestione/detailb.html
{% extends 'basebs.html' %}

{% load crispy_forms_tags %} 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

{% block title %} Dettagli di {{object.titolo}} {% endblock %} 

{% block header1 %}
  <h1> {{object}}</h1>
{% endblock %}

{% block content %} 

<br>
<div class="card">
  <div class="card-header">
     Libro con id {{ object.pk }}
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ object.titolo }} di {{object.autore}} </h5>
    <p class="card-text"> 
      <ul>
            {% for c in object.copie.all %}

            <li>  Copia con id: {{c.pk}} 
               {% if c.data_prestito  %}
                 in prestito a {{ c.utente.username }} dal {{ c.data_prestito }}
               {% else %} 
                  Attualmente non in prestito.
                {% endif %}
            </li>

            {% endfor %}
      </ul>
    </p>
  </div>
</div>
<br>


{% endblock %}

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/biblio3auth/biblio3/gestione/templates/gestione/home.html
{% extends 'basebs.html' %}

{% block title %} Home di Gestione {% endblock %} 

{% block header1 %}
  <h1>Home di Gestione</h1>
  <p>Welcome 
    {% if user.is_authenticated %}
     {{ user.username }}
    {% else %}
    Utente non registrato
    {% endif %}
  </p> 
{% endblock %}

{% block content %} 

<h2>Cosa vuoi fare oggi?</h2>

<br>

<div class="list-group">
  <a href="{% url 'gestione:cercalibro' %}" class="list-group-item list-group-item-info">Cerca un libro</a>
  <a href="{% url 'gestione:listalibri' %}" class="list-group-item list-group-item-info">Lista dei titoli</a>
  <a href="{% url 'gestione:situation' %}" class="list-group-item list-group-item-info">La mia situazione</a>
</div>

<br>

{% if user.is_staff %}
<br>
<a href="{% url 'registerb' %}" class="list-group-item list-group-item-danger">Iscrivi un bibliotecario</a>
<br>
{% endif %}


{% if "Bibliotecari" in user.groups.all.0.name or user.is_staff %}
<br>
<a href="{% url 'gestione:situationb' %}" class="list-group-item list-group-item-warning">Situazione Biblioteca</a>
<a href="{% url 'gestione:crealibro' %}" class="list-group-item list-group-item-warning">Aggiungi un libro</a>
<a href="{% url 'gestione:creacopia' %}" class="list-group-item list-group-item-warning">Aggiungi una copia</a>
<br>
{% endif %}


{% endblock %}

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/biblio3auth/biblio3/gestione/templates/gestione/lista_libri.html
{% extends 'basebs.html' %}

{% block title %} Lista dei libri{% endblock %} 

{% block header1 %}
  <h1>Lista dei Libri</h1>
{% endblock %}

{% block content %} 

<h2> {{ view.titolo }} {{ object_list.count }} libri </h2>

<br>

{% for l in object_list %}
<br>
<div class="card">
  <div class="card-header">
    {% if l.disponibile %}
     Libro disponibile per il prestito
    {% else %}
     Libro attualmente non disponibile
     {% endif %}
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ l.titolo }}</h5>
    <p class="card-text">Un libro di {{ l.autore }} di ben {{ l.pagine }} pagine...</p>

    {% if l.disponibile %}
    <a href="{% url 'gestione:prestito' l.pk %}" class="btn btn-info">
    {% else %}
    <a href="#" class="btn btn-info disabled">
    {% endif %}
    Prendilo in Prestito!</a> 

  </div>
</div>
<br>
{%endfor%}

<br>

{% endblock %}

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/biblio3auth/biblio3/gestione/templates/gestione/prestito.html
{% extends 'basebs.html' %}

{% load crispy_forms_tags %} 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

{% block title %} Prestito di {{libro.titolo}} {% endblock %} 

{% block header1 %}
  <h1>{{libro}}</h1>
{% endblock %}

{% block content %} 

{% if "NO_ERRORS" == errore %}
<div class="alert alert-success" role="alert">
  Il Prestito è andato a buon fine: hai ora la copia con id {{ copia.pk }}
{% else %}
<div class="alert alert-danger" role="alert">
  Prestito fallito: {{ errore }}
{% endif %}
</div>


{% endblock %}

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/biblio3auth/biblio3/gestione/templates/gestione/restituzione.html
{% extends 'basebs.html' %}

{% load crispy_forms_tags %} 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

{% block title %} Restituzione di {{object.libro.titolo}} {% endblock %} 

{% block header1 %}
  <h1>Copia con id {{object.pk}}</h1>
{% endblock %}

{% block content %} 

{% if "NO_ERRORS" == view.errore %}
<div class="alert alert-success" role="alert">
  La restituzione è andata a buon fine: la copia con id {{ copia.pk }} è di nuovo in biblioteca
{% else %}
<div class="alert alert-danger" role="alert">
  Restituzione fallita: {{ view.errore }}
{% endif %}
</div>


{% endblock %}

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/biblio3auth/biblio3/gestione/templates/gestione/ricerca.html
{% extends 'basebs.html' %}

{% block title %} Cerca tra i libri{% endblock %} 

{% load crispy_forms_tags %} 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

{% block header1 %}
  <h1>Cerca tra i libri</h1>
{% endblock %}

{% block content %} 

<h2> Cerca tra i libri </h2>

<br>

<br>

<div class="d-flex justify-content-center">

  {% crispy form %}

</div>
<br>


<br>

{% endblock %}

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/biblio3auth/biblio3/gestione/templates/gestione/ricerca_ajax.html
{% extends 'basebs.html' %}

{% block title %} Cerca tra i libri{% endblock %} 

{% load crispy_forms_tags %} 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

{% block header1 %}
  <h1>Cerca tra i libri</h1>
{% endblock %}

{% block content %} 

<h2> Cerca tra i libri </h2>

<br>

<br>

<div class="d-flex justify-content-center">

  {% crispy form %}

</div>
<br>

<br>

<script type="text/javascript">

  var stringText = document.getElementById("id_search_string");
  stringText.onkeyup = autoComplete;
  stringText.autocomplete = "off";

  function autoComplete(){

    var s = stringText.value;

    if(s.length<3){
        return;
    }
    else{

      const w = document.getElementById("id_search_where").value;
      const xhttp = new XMLHttpRequest();
      xhttp.onload = function() {

          if(xhttp.status == 200)
            stringText.value = this.responseText;
            
          console.log(this.responseText);
      }
      xhttp.open("GET", "gethint/?w=" + w + "&q=" + s);
      xhttp.send();
    }

  }


</script>

{% endblock %}

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/biblio3auth/biblio3/gestione/templates/gestione/situation.html
{% extends 'basebs.html' %}


{% block title %} Home di {{user.username}} {% endblock %} 

{% block header1 %}
  <h1>Home di {{user.username}} </h1>
  <p>Welcome 
    {% if user.is_authenticated %}
     {{ user.username }}
    {% else %}
    Utente non registrato
    {% endif %}
  </p> 
{% endblock %}

{% block content %} 

<h2>Risulta che hai correntemente in prestito: {{ listacopie.count }} copie </h2>

<p> Ulteriori dettagli </p>

<br>

{% for c in listacopie %}
<br>
<div class="card">
  <div class="card-header">
     Copia con id {{ c.pk }}
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ c.libro.titolo }}</h5>
    <p class="card-text">Un libro di {{ c.libro.autore }} di ben {{ c.libro.pagine }} pagine...</p>
    
    <a href="{% url 'gestione:restituzione' c.pk %}" class="btn btn-info"> Restituiscimi </a> 

  </div>
</div>
<br>
{%endfor%}

<br>

{% endblock %}

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/biblio3auth/biblio3/gestione/templates/gestione/situationb.html
{% extends 'basebs.html' %}


{% block title %} Situazione Biblioteca {% endblock %} 

{% block header1 %}
  <h1>Loggato come {{user.username}} </h1>
  <p>Welcome 
     {{ user.username }}
  </p> 
{% endblock %}

{% block content %} 

<h2> Stato attuale della biblioteca </h2>

<br>

{% for l in object_list  %}
<br>
<div class="card">
  <div class="card-header">
     Libro con id {{ l.pk }}
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ l.titolo }} di {{l.autore}} </h5>
    <p class="card-text"> {{ l }} </p>
    
    <a href="{% url 'gestione:detailb' l.pk %}" class="btn btn-info"> Visualizza Dettagli Aggiuntivi </a> 

  </div>
</div>
<br>
{%endfor%}

<br>

{% endblock %}