II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite_frameCBV/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .initcmds import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

#erase_db()
init_db()

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite_frameCBV/mysite/polls/urls.py
from django.urls import path

from .views import *

app_name = "polls"

urlpatterns = [
    path('', IndexViewList.as_view(), name='index'),
    path('<pk>/detail/', DetailQuestion.as_view(), name='detail'),

    path("search/", search, name="search"),
    path("searchresults/<str:sstring>/<str:where>/", SearchResultsList.as_view(), name="searchresults"),

    path("vote/<pk>/", vote, name="vote"),
    path("votecasted/<pk>/<str:answer>/", VoteCastedDetail.as_view(), name="votecasted"),

    path("createquestion/", CreateQuestionView.as_view(), name="createquestion"),
    path("createchoice/", CreateChoiceView.as_view(), name="createchoice")

]

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite_frameCBV/mysite/polls/models.py
from email.policy import default
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE,related_name="choices")
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite_frameCBV/mysite/polls/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from .models import *

class SearchForm(forms.Form):

    CHOICE_LIST = [("Questions","Search in Questions"), ("Choices","Search in Choices")]

    search_string = forms.CharField(label="Search String",max_length=100, min_length=3, required=True)
    search_where = forms.ChoiceField(label="Search Where?", required=True, choices=CHOICE_LIST)


class VoteForm(forms.Form):

    answer = forms.ModelChoiceField(queryset=None,required=True,label="Select your answer!")

    def __init__(self, pk, *args, **kwargs):
        super().__init__(*args, **kwargs)
        q = get_object_or_404(Question,pk=pk)
        self.fields['answer'].queryset = q.choices.all()



class CreateQuestionForm(forms.ModelForm):

    description = "Create a new Question!"

    def clean(self):

        if (len(self.cleaned_data["question_text"]) < 5):
            self.add_error("question_text", "Error: question text must be at least 5 characters long")

        return self.cleaned_data


    class Meta:
        model = Question
        fields = "__all__"
        widgets = {
        'pub_date': forms.DateInput(format=('%d/%m/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'})
        }


class CreateChoiceForm(forms.ModelForm):

    description = "Create choices for a question"

    def clean(self):

        q = get_object_or_404(Question,pk=self.cleaned_data["question"].id)

        choices = q.choices.all()
        choices_false = choices.filter(is_correct=False)

        if(choices.count()==4):
            self.add_error("question", "Error: question already has four options")
        elif(choices.count()==3):
            if choices_false.count()==3 and self.cleaned_data["is_correct"] == False:
                self.add_error("is_correct", "Error: exactly one choice must be correct")
        
        if (choices.filter(is_correct=True).count()==1 and self.cleaned_data["is_correct"] == True):
            self.add_error("is_correct", "Error: This question already has a correct answer")

        return self.cleaned_data

    class Meta:
        model = Choice
        fields = "__all__"

#Esempio Crispy Form helpers
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class VoteFormCrispy(VoteForm):

    helper = FormHelper()
    helper.form_id = "vote_crispy_form"
    helper.form_method = "POST"
    helper.add_input(Submit("submit","Vote!"))

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite_frameCBV/mysite/polls/views.py
from django.urls import reverse_lazy, reverse
from .models import *
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.shortcuts import get_object_or_404, redirect, render
from .forms import *

# Create your views here.

class IndexViewList(ListView):
    model = Question
    template_name = 'polls/index.html'

    def get_queryset(self):
        return self.model.objects.order_by('-pub_date')[:20]

class DetailQuestion(DetailView):
    model = Question
    template_name = "polls/detail.html"

##########Form

def search(request):

    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            sstring = form.cleaned_data.get("search_string")
            where = form.cleaned_data.get("search_where")
            return redirect("polls:searchresults", sstring, where)
    else:
        form = SearchForm()

    return render(request,template_name="polls/searchpage.html",context={"form":form})
    #return render(request,template_name="polls/crispyf/searchpage.html",context={"form":form})

class SearchResultsList(ListView):

    model = Question
    template_name = "polls/searchresults.html"

    def get_queryset(self):
        sstring = self.request.resolver_match.kwargs["sstring"] 
        where = self.request.resolver_match.kwargs["where"]

        if "Question" in where:
            qq = Question.objects.filter(question_text__icontains=sstring)
        else:
            qc = Choice.objects.filter(choice_text__icontains=sstring)
            qq = Question.objects.none()
            for c in qc:
                qq |= Question.objects.filter(pk=c.question_id)

        return qq

##########ModelChoiceField

def vote(request, pk):

    if request.method == "POST":
        form = VoteForm(data=request.POST, pk=pk)
        #form = VoteFormCrispy(data=request.POST, pk=pk)
        if form.is_valid():
            answer = form.cleaned_data.get("answer")
            return redirect("polls:votecasted", pk, answer.choice_text)
    else:
        q = get_object_or_404(Question,pk=pk)
        form = VoteForm(pk=pk)
        #form = VoteFormCrispy(pk=pk)
        return render(request,template_name="polls/crispyf/vote.html",context={"form":form,"question":q})
        #return render(request,template_name="polls/vote.html",context={"form":form,"question":q})

class VoteCastedDetail(DetailView):
    model = Question
    template_name = "polls/votecasted.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        answer = self.request.resolver_match.kwargs["answer"]
        ctx["answer"] = answer
        correct = ctx["object"].choices.all().get(is_correct=True) 
        if answer in correct.choice_text:
            ctx["message"] = "Right Answer!"
        else:
            ctx["message"] = "Wrong Answer! " + " The right answer was " + str(correct.choice_text)

        try:
            c = ctx["object"].choices.all().get(choice_text=answer) 
            c.votes += 1
            c.save()
        except Exception as e:
            print("Impossible to update vote value " + str(e))

        return ctx

##########Model Forms

class CreateQuestionView(CreateView):
    template_name = "polls/createentry.html"
    #template_name = "polls/crispyf/createentry.html"
    form_class = CreateQuestionForm
    success_url = reverse_lazy("polls:index")

class CreateChoiceView(CreateView):
    template_name = "polls/createentry.html"
    #template_name = "polls/crispyf/createentry.html"
    form_class = CreateChoiceForm

    def get_success_url(self):
        ctx = self.get_context_data()
        pk = ctx["object"].question.pk
        return reverse("polls:detail",kwargs={"pk":pk})

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite_frameCBV/mysite/polls/templates/polls/crispyf/createentry.html
{% extends "base.html" %}

{% block head %} 
{% load crispy_forms_tags %} 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 
{% endblock %}

{% block title %} {{  view.form_class.description  }} {% endblock %}

{% block content %}

<center>
<h1> {{ view.form_class.description }}  </h1>
</center>

<div class="d-flex justify-content-center">
<form method="POST">  {% csrf_token %}

    {{form|crispy}}

<input type="submit" value="Create">
</form>
</div>

{% endblock %}

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite_frameCBV/mysite/polls/templates/polls/crispyf/searchpage.html
{% extends "base.html" %}

{% block head %} 
{% load crispy_forms_tags %} 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 
{% endblock %}

{% block title %} Search Page Form {% endblock %}

{% block content %}

<center>
    <h1>Search Page</h1>
</center>

<div class="d-flex justify-content-center">

<form action="{% url 'polls:search' %}" method="POST">  {% csrf_token %}

    {{form|crispy}}

<input type="submit" value="Search">

</div>

{% endblock %}

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite_frameCBV/mysite/polls/templates/polls/crispyf/vote.html
{% extends "base.html" %}

{% block head %} 

{% load crispy_forms_tags %} 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 
{% endblock %}

{% block title %} Vote Page Form {% endblock %}

{% block content %}

<center>
<h1>Vote Page</h1>

<p>
{{question.question_text}}
</p>

</center>

<div class="d-flex justify-content-center">

    {% crispy form %}

</div>

{% endblock %}

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite_frameCBV/mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block head %} {% endblock %}
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>