II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .initcmds import *

urlpatterns = [
   
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

#erase_db()
init_db()

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite/mysite/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('recent/<int:n_polls>', views.recent, name='recent'),
]

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite/mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from .models import *

# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:20]
    template = loader.get_template('polls/index.html')
    context = {'latest_question_list': latest_question_list}
    return HttpResponse(template.render(context,request))

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def recent(request, n_polls):
    question_list_ord = Question.objects.order_by('-pub_date')
    latest_question_list = []
    for q in question_list_ord:
        if q.was_published_recently():
            latest_question_list.append(q)

    context = {'latest_question_list':latest_question_list[:int(n_polls)]}
    return render(request, 'polls/index.html', context)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite/mysite/polls/templates/polls/detail.html
{% extends "base.html" %}

{% block content %}

<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:results' question.id %}">See results?</a>

{% endblock %}

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite/mysite/polls/templates/polls/index.html
{% extends "base.html" %}


{% block content %}

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

II SEMESTRE/TECNOLOGIE/techweb-main-capodieci/django/mysite/mysite/polls/templates/polls/results.html
{% extends "base.html" %}

{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock %}